name: Lunar Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 0xWelt/Lunar@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # # Optional, change as you wish or comment out to use default
          # LLM settings
          OPENAI_BASE_URL: https://api.deepseek.com/v1 # https://api.openai.com/v1
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: deepseek-chat # gpt-4o-mini
          TEMPERATURE: 1.0 # 1.0
          MAX_TOKENS: 8192 # 4096
          # Lunar settings
          LANGUAGE: Chinese # Chinese
          IGNORE_PATTERNS: autowsgr/data/**/* # glob pattern or regex pattern to ignore files, separated by comma
